services:
  h2:
    image: oscarfonts/h2
    container_name: h2
    ports:
      - "81:81"  # H2 web console
      - "1521:1521"  # H2 TCP server
    environment:
      - H2_OPTIONS=-ifNotExists
    volumes:
      - "./h2:/opt/h2-data"